import { TemplateType } from '../types';

export interface TemplateTheme {
  id: TemplateType;
  name: string;
  description: string;
  headerBg: string;
  avatarRing: string;
  badgeBg: string;
  badgeText: string;
  saveContactBtn: string;
  actionBtnPrimary: string;
  actionBtnSecondary: string;
  actionBtnIcon: string;
  cardBg: string;
  cardBorder: string;
  sectionTitle: string;
  accentText: string;
  accentBg: string;
  ctaBtn: string;
}

export const TEMPLATE_THEMES: Record<TemplateType, TemplateTheme> = {
  professional: {
    id: 'professional',
    name: 'Professional',
    description: 'Clean indigo & slate for modern professionals and tech leaders',
    headerBg: 'bg-gradient-to-b from-indigo-950 via-slate-900 to-slate-950 text-white',
    avatarRing: 'ring-4 ring-indigo-500/50 shadow-xl',
    badgeBg: 'bg-indigo-500/20 border border-indigo-400/30',
    badgeText: 'text-indigo-200',
    saveContactBtn: 'bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-500 hover:to-blue-500 text-white shadow-lg shadow-indigo-600/30',
    actionBtnPrimary: 'bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200',
    actionBtnSecondary: 'bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200',
    actionBtnIcon: 'text-indigo-600',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200/80',
    sectionTitle: 'text-slate-900',
    accentText: 'text-indigo-600',
    accentBg: 'bg-indigo-50',
    ctaBtn: 'bg-slate-900 hover:bg-slate-800 text-white',
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate',
    description: 'Refined deep royal blue & steel for finance, legal & corporate leaders',
    headerBg: 'bg-gradient-to-b from-blue-950 via-slate-900 to-slate-950 text-white',
    avatarRing: 'ring-4 ring-blue-500/50 shadow-xl',
    badgeBg: 'bg-blue-500/20 border border-blue-400/30',
    badgeText: 'text-blue-200',
    saveContactBtn: 'bg-gradient-to-r from-blue-700 to-cyan-700 hover:from-blue-600 hover:to-cyan-600 text-white shadow-lg shadow-blue-700/30',
    actionBtnPrimary: 'bg-blue-50 hover:bg-blue-100 text-blue-800 border border-blue-200',
    actionBtnSecondary: 'bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200',
    actionBtnIcon: 'text-blue-700',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200/80',
    sectionTitle: 'text-slate-900',
    accentText: 'text-blue-700',
    accentBg: 'bg-blue-50',
    ctaBtn: 'bg-blue-900 hover:bg-blue-800 text-white',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'High-contrast monochrome Swiss modernist aesthetic',
    headerBg: 'bg-gradient-to-b from-zinc-950 via-zinc-900 to-black text-white',
    avatarRing: 'ring-4 ring-zinc-600 shadow-xl',
    badgeBg: 'bg-zinc-800 border border-zinc-700',
    badgeText: 'text-zinc-300',
    saveContactBtn: 'bg-zinc-900 hover:bg-black text-white border border-zinc-700 shadow-lg shadow-black/20',
    actionBtnPrimary: 'bg-zinc-100 hover:bg-zinc-200 text-zinc-900 border border-zinc-300',
    actionBtnSecondary: 'bg-zinc-50 hover:bg-zinc-100 text-zinc-700 border border-zinc-200',
    actionBtnIcon: 'text-zinc-900',
    cardBg: 'bg-white',
    cardBorder: 'border-zinc-200',
    sectionTitle: 'text-zinc-900',
    accentText: 'text-zinc-900',
    accentBg: 'bg-zinc-100',
    ctaBtn: 'bg-black hover:bg-zinc-800 text-white',
  },
  executive: {
    id: 'executive',
    name: 'Executive',
    description: 'Distinguished deep emerald & charcoal for C-suite and founders',
    headerBg: 'bg-gradient-to-b from-emerald-950 via-slate-900 to-slate-950 text-white',
    avatarRing: 'ring-4 ring-emerald-500/50 shadow-xl',
    badgeBg: 'bg-emerald-500/20 border border-emerald-400/30',
    badgeText: 'text-emerald-200',
    saveContactBtn: 'bg-gradient-to-r from-emerald-700 to-teal-800 hover:from-emerald-600 hover:to-teal-700 text-white shadow-lg shadow-emerald-800/30',
    actionBtnPrimary: 'bg-emerald-50 hover:bg-emerald-100 text-emerald-900 border border-emerald-200',
    actionBtnSecondary: 'bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200',
    actionBtnIcon: 'text-emerald-700',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200/80',
    sectionTitle: 'text-slate-900',
    accentText: 'text-emerald-700',
    accentBg: 'bg-emerald-50',
    ctaBtn: 'bg-emerald-950 hover:bg-emerald-900 text-white',
  },
  creative: {
    id: 'creative',
    name: 'Creative',
    description: 'Vibrant violet-fuchsia glow for designers, creators and agencies',
    headerBg: 'bg-gradient-to-b from-violet-950 via-fuchsia-950 to-slate-950 text-white',
    avatarRing: 'ring-4 ring-fuchsia-500/50 shadow-xl',
    badgeBg: 'bg-fuchsia-500/20 border border-fuchsia-400/30',
    badgeText: 'text-fuchsia-200',
    saveContactBtn: 'bg-gradient-to-r from-violet-600 via-fuchsia-600 to-pink-600 hover:from-violet-500 hover:to-pink-500 text-white shadow-lg shadow-fuchsia-600/30',
    actionBtnPrimary: 'bg-fuchsia-50 hover:bg-fuchsia-100 text-fuchsia-900 border border-fuchsia-200',
    actionBtnSecondary: 'bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200',
    actionBtnIcon: 'text-violet-600',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200/80',
    sectionTitle: 'text-slate-900',
    accentText: 'text-fuchsia-600',
    accentBg: 'bg-fuchsia-50',
    ctaBtn: 'bg-gradient-to-r from-violet-900 to-fuchsia-900 hover:from-violet-800 hover:to-fuchsia-800 text-white',
  },
  medical: {
    id: 'medical',
    name: 'Medical',
    description: 'Calming oceanic teal & clean trust for doctors, clinics and health experts',
    headerBg: 'bg-gradient-to-b from-teal-950 via-cyan-950 to-slate-950 text-white',
    avatarRing: 'ring-4 ring-teal-400/50 shadow-xl',
    badgeBg: 'bg-teal-500/20 border border-teal-400/30',
    badgeText: 'text-teal-200',
    saveContactBtn: 'bg-gradient-to-r from-teal-600 to-cyan-600 hover:from-teal-500 hover:to-cyan-500 text-white shadow-lg shadow-teal-600/30',
    actionBtnPrimary: 'bg-teal-50 hover:bg-teal-100 text-teal-800 border border-teal-200',
    actionBtnSecondary: 'bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200',
    actionBtnIcon: 'text-teal-600',
    cardBg: 'bg-white',
    cardBorder: 'border-teal-100/80',
    sectionTitle: 'text-slate-900',
    accentText: 'text-teal-700',
    accentBg: 'bg-teal-50',
    ctaBtn: 'bg-teal-800 hover:bg-teal-700 text-white',
  },
  business: {
    id: 'business',
    name: 'Business',
    description: 'Warm amber & sandstone for consultants, real estate & advisory',
    headerBg: 'bg-gradient-to-b from-stone-950 via-amber-950 to-stone-900 text-white',
    avatarRing: 'ring-4 ring-amber-500/50 shadow-xl',
    badgeBg: 'bg-amber-500/20 border border-amber-400/30',
    badgeText: 'text-amber-200',
    saveContactBtn: 'bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 text-white shadow-lg shadow-amber-600/30',
    actionBtnPrimary: 'bg-amber-50 hover:bg-amber-100 text-amber-900 border border-amber-200',
    actionBtnSecondary: 'bg-stone-50 hover:bg-stone-100 text-stone-700 border border-stone-200',
    actionBtnIcon: 'text-amber-700',
    cardBg: 'bg-white',
    cardBorder: 'border-stone-200/80',
    sectionTitle: 'text-stone-900',
    accentText: 'text-amber-700',
    accentBg: 'bg-amber-50',
    ctaBtn: 'bg-stone-900 hover:bg-stone-800 text-white',
  },
  luxury: {
    id: 'luxury',
    name: 'Luxury',
    description: 'Black obsidian with brushed champagne gold for architects, jewelers & luxury brands',
    headerBg: 'bg-gradient-to-b from-black via-zinc-950 to-zinc-900 text-white',
    avatarRing: 'ring-4 ring-amber-400/70 shadow-2xl',
    badgeBg: 'bg-amber-400/10 border border-amber-400/30',
    badgeText: 'text-amber-300',
    saveContactBtn: 'bg-gradient-to-r from-amber-300 via-amber-200 to-yellow-400 hover:from-amber-200 hover:to-yellow-300 text-black font-semibold shadow-lg shadow-amber-400/20',
    actionBtnPrimary: 'bg-zinc-900 hover:bg-zinc-800 text-amber-300 border border-amber-500/30',
    actionBtnSecondary: 'bg-zinc-950 hover:bg-zinc-900 text-zinc-300 border border-zinc-800',
    actionBtnIcon: 'text-amber-400',
    cardBg: 'bg-zinc-950 text-white',
    cardBorder: 'border-zinc-800',
    sectionTitle: 'text-amber-200',
    accentText: 'text-amber-400',
    accentBg: 'bg-zinc-900',
    ctaBtn: 'bg-amber-400 hover:bg-amber-300 text-black font-semibold',
  },
};
